# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let inherit (builtins) readFile;
  nvidia-offload = pkgs.writeShellScriptBin "nvidia-offload" ''
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export __VK_LAYER_NV_optimus=NVIDIA_only
    exec -a "$0" "$@"
  '';
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot = {

    initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" ];
    initrd.kernelModules = [ ];

    extraModulePackages = [ ];
    kernelModules = [ "kvm-intel" ];
    kernelPackages = pkgs.linuxPackages_latest;

    tmpOnTmpfs = true;

    kernel.sysctl."kernel.sysrq" = 1;

  };

  environment = {

    systemPackages = with pkgs; [
    nvidia-offload
    ];
  };


  # should certain parts of xserver be host specific
  # and other parts profile specific?
  services.xserver.videoDrivers = [ "modesetting" "nvidia" "intel" ];

  hardware.nvidia.prime = {
    offload.enable = true;

    # Bus ID of the Intel GPU. You can find it using lspci, either under 3D or VGA
    intelBusId = "PCI:0:2:0";

    # Bus ID of the NVIDIA GPU. You can find it using lspci, either under 3D or VGA
    nvidiaBusId = "PCI:1:0:0";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c5c1f122-1627-4111-9060-8e600862ca4f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4404-6493";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # does this change when I use the charger?
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
